version: "3"
services:
  app:
    env_file:
      - .env
    build: .
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - borsch-playground-network
networks:
  borsch-playground-network:
    external: true
